#!/bin/bash
set -e
openwisp-utils-qa-checks \
    --migration-path ./openwisp_firmware_upgrader/migrations \
    --migration-module firmware_upgrader

export SAMPLE_APP=1
openwisp-utils-qa-checks \
    --skip-isort \
    --skip-flake8 \
    --skip-checkmigrations \
    --skip-checkendline \
    --skip-checkcommit \
    --migration-path ./tests/openwisp2/sample_firmware_upgrader/migrations/ \
    --migration-module sample_firmware_upgrader
unset SAMPLE_APP
