# Generated by Django 3.0.8 on 2020-07-07 17:00

from django.db import migrations, models

from . import create_device_firmware_for_connections


def create_device_firmware_for_connections_helper(apps, schema_editor):
    app_label = 'firmware_upgrader'
    create_device_firmware_for_connections(apps, schema_editor, app_label)


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_upgrader', '0004_batch_upgrade_operation_idle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='os_identifier',
            field=models.CharField(
                blank=True,
                help_text='OS identifier as presented by the device, used to automatically recognize the firmware image used by new devices that register into the system',
                max_length=64,
                null=True,
            ),
        ),
        migrations.RunPython(
            create_device_firmware_for_connections_helper,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
