# Generated by Django 4.0.4 on 2022-04-20 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_upgrader', '0008_firmware_image_baseurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchupgradeoperation',
            name='build_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchupgradeoperation',
            name='build',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.FIRMWARE_UPGRADER_BUILD_MODEL,
            ),
        ),
    ]
