# Generated by Django 4.2.16 on 2025-02-20 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0020_populate_password_updated_field"),
        ("firmware_upgrader", "0010_alter_firmwareimage_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="openwisp_users.organization",
                verbose_name="organization",
            ),
        ),
    ]
