# Generated by Django 5.2.3 on 2025-07-09 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0011_alter_category_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradeoperation",
            name="progress",
            field=models.IntegerField(
                default=0,
                help_text="Upgrade progress percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
