# Generated by Django 5.2.5 on 2025-08-27 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0012_update_image_type_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradeoperation",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
