# Generated by Django 5.2.4 on 2025-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0013_upgradeoperation_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("in-progress", "in progress"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                    ("aborted", "aborted"),
                ],
                default="in-progress",
                max_length=12,
            ),
        ),
    ]
