# Generated by Django 5.2.5 on 2025-09-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0015_add_group_to_batchupgradeoperation"),
        migrations.swappable_dependency(settings.GEO_LOCATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.GEO_LOCATION_MODEL,
                verbose_name="location",
            ),
        ),
    ]
