# Generated by Django 5.2.11 on 2026-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0016_batchupgradeoperation_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchupgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("in-progress", "in progress"),
                    ("success", "completed successfully"),
                    ("failed", "completed with some failures"),
                    ("cancelled", "completed with some cancellations"),
                ],
                default="idle",
                max_length=12,
            ),
        ),
    ]
