# Generated by Django 5.2.15 on 2026-08-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0018_batchupgradeoperation_is_persistent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="firmwareless",
            field=models.BooleanField(
                default=False,
                help_text="whether to include devices that have no existing firmware record when this mass upgrade launches",
                verbose_name="firmwareless",
            ),
        ),
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="future date and time at which this mass upgrade is launched, null for an immediate upgrade",
                null=True,
                verbose_name="scheduled at",
            ),
        ),
        migrations.AlterField(
            model_name="batchupgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("scheduled", "scheduled"),
                    ("in-progress", "in progress"),
                    ("success", "completed successfully"),
                    ("failed", "completed with some failures"),
                    ("cancelled", "completed with some cancellations"),
                ],
                default="idle",
                max_length=12,
            ),
        ),
    ]
