# Generated by Django 5.2.15 on 2026-06-30 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0019_batchupgradeoperation_last_reminder_at"),
        migrations.swappable_dependency(settings.CONFIG_DEVICEGROUP_MODEL),
        migrations.swappable_dependency(settings.GEO_LOCATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="firmwareless",
            field=models.BooleanField(
                default=False,
                help_text="whether to include devices that have no existing firmware record when this mass upgrade launches",
                verbose_name="firmwareless",
            ),
        ),
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="future date and time (UTC) at which this mass upgrade is launched, null for an immediate upgrade",
                null=True,
                verbose_name="scheduled at",
            ),
        ),
        migrations.AlterField(
            model_name="batchupgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("scheduled", "scheduled"),
                    ("in-progress", "in progress"),
                    ("success", "completed successfully"),
                    ("failed", "completed with some failures"),
                    ("cancelled", "completed with some cancellations"),
                ],
                default="idle",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="batchupgradeoperation",
            index=models.Index(
                fields=["status", "scheduled_at"], name="firmware_up_status_5031c1_idx"
            ),
        ),
    ]
