# Generated by Django 5.2.14 on 2026-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0019_backfill_extraction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmwareimage",
            name="board",
            field=models.CharField(blank=True, max_length=200, verbose_name="board"),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="compat_version",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="compat version"
            ),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="compatible",
            field=models.JSONField(blank=True, default=list, verbose_name="compatible"),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="extraction_log",
            field=models.TextField(blank=True, verbose_name="extraction log"),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unsupported_format", "Unsupported format"),
                    ("out_of_memory", "Out of memory"),
                    ("invalid_file", "Invalid file"),
                    ("timeout", "Extraction timed out"),
                ],
                default="",
                max_length=20,
                verbose_name="failure reason",
            ),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="source",
            field=models.CharField(blank=True, max_length=20, verbose_name="source"),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="target",
            field=models.CharField(blank=True, max_length=100, verbose_name="target"),
        ),
    ]
