# Generated by Django 5.2.15 on 2026-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0020_alter_firmwareimage_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmwareimage",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="firmware image type: model or architecture. Leave blank to attempt determining automatically",
                max_length=128,
            ),
        ),
    ]
