# Generated by Django 5.2.15 on 2026-07-02 18:26

from django.db import migrations, models


def convert_compatible_to_text(apps, schema_editor):
    FirmwareImage = apps.get_model("firmware_upgrader", "FirmwareImage")
    table = FirmwareImage._meta.db_table
    for image in FirmwareImage.objects.iterator():
        if isinstance(image.compatible, list) and image.compatible:
            text_value = "\n".join(image.compatible)
            schema_editor.execute(
                f"UPDATE {table} SET compatible = %s WHERE id = %s",
                [text_value, str(image.pk)],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0021_firmwareimage_remove_type_choices"),
    ]

    operations = [
        migrations.RunPython(convert_compatible_to_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="firmwareimage",
            name="compatible",
            field=models.TextField(blank=True, default="", verbose_name="compatible"),
        ),
    ]
