# Generated by Django 5.2.15 on 2026-07-02 18:26

import json
import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def convert_compatible_to_text(apps, schema_editor):
    FirmwareImage = apps.get_model("firmware_upgrader", "FirmwareImage")
    batch = []
    for image in FirmwareImage.objects.iterator():
        try:
            value = json.loads(image.compatible or "null")
        except (json.JSONDecodeError, TypeError):
            continue
        if isinstance(value, list):
            string_items = [item for item in value if isinstance(item, str)]
            if len(string_items) != len(value):
                logger.warning(
                    "convert_compatible_to_text: FirmwareImage pk=%s has "
                    "non-string items in its compatible list, dropping them",
                    image.pk,
                )
            image.compatible = "\n".join(string_items)
            batch.append(image)
            if len(batch) >= 500:
                FirmwareImage.objects.bulk_update(batch, ["compatible"])
                batch.clear()
        else:
            logger.warning(
                "convert_compatible_to_text: skipping FirmwareImage pk=%s, "
                "compatible field is valid JSON but not a list",
                image.pk,
            )
    if batch:
        FirmwareImage.objects.bulk_update(batch, ["compatible"])


def convert_compatible_to_json(apps, schema_editor):
    FirmwareImage = apps.get_model("firmware_upgrader", "FirmwareImage")
    batch = []
    for image in FirmwareImage.objects.iterator():
        lines = [line for line in (image.compatible or "").splitlines() if line]
        image.compatible = json.dumps(lines)
        batch.append(image)
        if len(batch) >= 500:
            FirmwareImage.objects.bulk_update(batch, ["compatible"])
            batch.clear()
    if batch:
        FirmwareImage.objects.bulk_update(batch, ["compatible"])


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0021_firmwareimage_remove_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmwareimage",
            name="compatible",
            field=models.TextField(blank=True, default="", verbose_name="compatible"),
        ),
        migrations.RunPython(convert_compatible_to_text, convert_compatible_to_json),
    ]
