# Generated by Django 5.2.15 on 2026-07-02 18:26

from django.db import migrations, models


def convert_compatible_to_text(apps, schema_editor):
    FirmwareImage = apps.get_model("firmware_upgrader", "FirmwareImage")
    for image in FirmwareImage.objects.exclude(compatible=[]).iterator():
        if isinstance(image.compatible, list):
            FirmwareImage.objects.filter(pk=image.pk).update(
                compatible="\n".join(image.compatible)
            )


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0021_firmwareimage_remove_type_choices"),
    ]

    operations = [
        migrations.RunPython(convert_compatible_to_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="firmwareimage",
            name="compatible",
            field=models.TextField(blank=True, default="", verbose_name="compatible"),
        ),
    ]
