# Generated by Django 3.0.5 on 2020-05-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0007_unique_email'),
        ('sample_firmware_upgrader', '0003_private_media'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='build', unique_together={('category', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='category', unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='firmwareimage', unique_together={('build', 'type')},
        ),
    ]
