# Generated by Django 3.0.5 on 2020-05-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0007_unique_email'),
        ('sample_firmware_upgrader', '0003_private_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchupgradeoperation',
            options={
                'verbose_name': 'Mass upgrade operation',
                'verbose_name_plural': 'Mass upgrade operations',
            },
        ),
        migrations.AlterModelOptions(
            name='build',
            options={
                'ordering': ('-created',),
                'verbose_name': 'Firmware Build',
                'verbose_name_plural': 'Firmware Builds',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'Firmware Category',
                'verbose_name_plural': 'Firmware Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='devicefirmware', options={'verbose_name': 'Device Firmware'},
        ),
        migrations.AlterModelOptions(
            name='firmwareimage',
            options={
                'verbose_name': 'Firmware Image',
                'verbose_name_plural': 'Firmware Images',
            },
        ),
        migrations.AlterUniqueTogether(
            name='build', unique_together={('category', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='category', unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='firmwareimage', unique_together={('build', 'type')},
        ),
    ]
