# Generated by Django 5.2.12 on 2026-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0004_alter_firmwareimage_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="is_persistent",
            field=models.BooleanField(
                default=True,
                help_text="if enabled, the mass upgrade keeps retrying offline devices until they come back online or the operation is cancelled",
                verbose_name="persistent",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="is_persistent",
            field=models.BooleanField(
                default=False,
                help_text="if enabled, the operation stays pending and retries when the device comes back online",
                verbose_name="persistent",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="next_retry_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="when the periodic scanner should next retry this pending operation, null if no retry is queued",
                null=True,
                verbose_name="next retry at",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="number of times the operation has gone from in-progress to pending",
                verbose_name="retry count",
            ),
        ),
        migrations.AlterField(
            model_name="upgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("in-progress", "in progress"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                    ("aborted", "aborted"),
                    ("pending", "pending"),
                ],
                default="in-progress",
                max_length=12,
            ),
        ),
    ]
