# Generated by Django 3.0.5 on 2020-06-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_firmware_upgrader', '0004_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchupgradeoperation',
            name='status',
            field=models.CharField(
                choices=[
                    ('idle', 'idle'),
                    ('in-progress', 'in progress'),
                    ('success', 'completed successfully'),
                    ('failed', 'completed with some failures'),
                ],
                default='idle',
                max_length=12,
            ),
        )
    ]
