# Generated by Django 5.2.12 on 2026-05-26 12:45

# Adding next_retry_at with db_index=True makes this migration build a btree
# index on the upgrade-operation table. On PostgreSQL the non-concurrent
# CREATE INDEX takes a SHARE lock that blocks writes (reads keep working) for
# the duration of the build, so if the table has grown large, run this
# migration in a maintenance window.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0004_alter_firmwareimage_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="is_persistent",
            field=models.BooleanField(
                default=False,
                help_text="if enabled, the system will keep retrying upgrades for offline devices until they succeed or are cancelled",
                verbose_name="persistent",
            ),
        ),
        migrations.AlterField(
            model_name="batchupgradeoperation",
            name="is_persistent",
            field=models.BooleanField(
                default=True,
                help_text="if enabled, the system will keep retrying upgrades for offline devices until they succeed or are cancelled",
                verbose_name="persistent",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="is_persistent",
            field=models.BooleanField(
                default=False,
                help_text="if enabled, the system will keep retrying this upgrade until it succeeds or is cancelled",
                verbose_name="persistent",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="next_retry_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="date and time of the next retry attempt",
                null=True,
                verbose_name="next retry at",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="number of retry attempts made for this upgrade",
                verbose_name="retry count",
            ),
        ),
        migrations.AlterField(
            model_name="upgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("in-progress", "in progress"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                    ("aborted", "aborted"),
                    ("pending", "pending"),
                ],
                default="in-progress",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="last_reminder_at",
            field=models.DateTimeField(
                blank=True,
                help_text="timestamp of the last pending-upgrade reminder fired for this batch, null if no reminder has been sent yet",
                null=True,
                verbose_name="last reminder at",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="time the persistent upgrade was claimed for dispatch",
                null=True,
                verbose_name="claimed at",
            ),
        ),
    ]
