# Generated by Django 5.2.5 on 2025-09-03 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0005_upgradeoperation_progress"),
        migrations.swappable_dependency(settings.CONFIG_DEVICEGROUP_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.CONFIG_DEVICEGROUP_MODEL,
                verbose_name="device group",
            ),
        ),
    ]
