# Generated by Django 5.2.12 on 2026-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sample_firmware_upgrader",
            "0005_batchupgradeoperation_is_persistent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="last_reminder_at",
            field=models.DateTimeField(
                blank=True,
                help_text="timestamp of the last pending-upgrade reminder fired for this batch, null if no reminder has been sent yet",
                null=True,
                verbose_name="last reminder at",
            ),
        ),
    ]
