# Generated by Django 5.2.15 on 2026-07-03 09:07

from django.db import migrations, models


def convert_compatible_to_text(apps, schema_editor):
    FirmwareImage = apps.get_model("sample_firmware_upgrader", "FirmwareImage")
    for image in FirmwareImage.objects.exclude(compatible=[]).iterator():
        if isinstance(image.compatible, list):
            FirmwareImage.objects.filter(pk=image.pk).update(
                compatible="\n".join(image.compatible)
            )


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0006_alter_firmwareimage_board_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_compatible_to_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="firmwareimage",
            name="compatible",
            field=models.TextField(blank=True, default="", verbose_name="compatible"),
        ),
        migrations.AlterField(
            model_name="firmwareimage",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="firmware image type: model or architecture. Leave blank to attempt determining automatically",
                max_length=128,
            ),
        ),
    ]
