# Generated by Django 5.2.17 on 2026-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0010_firmwareimage_extraction_claimed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmwareimage",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("unconfirmed", "Unconfirmed"),
                    ("in_progress", "In Progress"),
                    ("success", "Success"),
                    ("incomplete", "Incomplete"),
                    ("failed", "Failed"),
                    ("manually_confirmed", "Manually Confirmed"),
                    ("invalid", "Invalid"),
                ],
                db_index=True,
                default="unconfirmed",
                max_length=20,
                verbose_name="extraction status",
            ),
        ),
    ]
