# Generated by Django 5.2.17 on 2026-08-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0011_alter_firmwareimage_extraction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="status",
            field=models.CharField(
                choices=[
                    ("analyzing", "Analyzing"),
                    ("success", "Success"),
                    ("incomplete", "Incomplete"),
                    ("failed", "Failed"),
                    ("invalid", "Invalid"),
                    ("manually_confirmed", "Manually Confirmed"),
                ],
                db_index=True,
                default="analyzing",
                max_length=20,
                verbose_name="extraction status",
            ),
        ),
    ]
